title: SiteTitle
description: description for your site.
signature: your signature.
nick_name: your nick name
nick_name_vcard: your nick name vcard.
email: your email address
show_downloads: true
theme: furendo
tags: default
paginate: 5
paginate_path: "/page:num/"
tag_page_layout: tag_page
tag_page_dir: tag
friends:
    - name: 友链1
      link: https://www.sample.com
    - name: 友链2
      link: https://www.sample.com
    